#!/usr/bin/env bash
#
# create-developer-id-certificate.sh
#
# Requests a "Developer ID Application" certificate from Apple through the
# App Store Connect API and packages it as the .p12 used by the publish
# workflow (see docs/macos-code-signing.md). Optionally uploads the
# CSC_LINK / CSC_KEY_PASSWORD repository secrets with the gh CLI.
#
# Requirements:
#   - an App Store Connect API key (.p8). Developer ID certificates can only
#     be created with a TEAM key GENERATED BY THE ACCOUNT HOLDER of the
#     Apple Developer team: being an Admin yourself is not enough, and
#     individual keys cannot use the certificate endpoints at all. If the
#     Account Holder is someone else, ask them to create the team key from
#     App Store Connect → Users and Access → Integrations → Team Keys.
#   - openssl, curl, jq (on macOS: brew install jq)
#
# Usage:
#   ./scripts/create-developer-id-certificate.sh \
#       --key-file AuthKey_XXXXXXXXXX.p8 \
#       --issuer-id 12345678-1234-1234-1234-123456789012 \
#       [options]
#
# Options:
#   --key-file <path>       App Store Connect API key (.p8)         (required)
#   --issuer-id <uuid>      Issuer ID from Users and Access → Integrations
#                                                                   (required)
#   --key-id <id>           API key ID, derived from the AuthKey_<ID>*.p8
#                           file name when omitted
#   --out-dir <dir>         output directory                        (default:
#                           ./developer-id-certificate)
#   --p12-password <pwd>    password for the exported .p12, prompted
#                           interactively when omitted
#   --upload-secrets        after the export, set the CSC_LINK and
#                           CSC_KEY_PASSWORD repository secrets via gh
#   --repo <owner/repo>     repository for --upload-secrets, defaults to the
#                           current directory's repository
#   --check                 only verify that the API credentials work, then
#                           exit without creating anything
#   --force                 overwrite an existing private key / .p12
#   -h, --help              this help

set -euo pipefail

# ── Configuration, overridable via the options above ──────────────────────
KEY_FILE=""
KEY_ID=""
ISSUER_ID=""
OUT_DIR="developer-id-certificate"
P12_PASSWORD=""
UPLOAD_SECRETS=0
GH_REPO=""
CHECK_ONLY=0
FORCE=0

API_BASE="https://api.appstoreconnect.apple.com/v1"
CSR_SUBJECT="/CN=ExpressLRS Configurator Developer ID/C=US"
TOKEN_LIFETIME_SECONDS=1140 # Apple rejects tokens valid for more than 20 min

# ── Helpers ───────────────────────────────────────────────────────────────
die() {
  echo "Error: $*" >&2
  exit 1
}

usage() {
  sed -n '2,/^set -euo pipefail/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

need() {
  command -v "$1" > /dev/null 2>&1 || die "'$1' is required but not installed$2"
}

b64url() {
  openssl base64 -A | tr '+/' '-_' | tr -d '='
}

# left pad a hex integer to 32 bytes, dropping DER sign padding
fixed32() {
  local hex
  hex="$(printf '%s' "$1" | sed 's/^0*//')"
  [ -n "$hex" ] || hex=0
  printf '%064s' "$hex" | tr ' ' '0'
}

hex2bin() {
  # shellcheck disable=SC2059
  printf "$(printf '%s' "$1" | sed 's/../\\x&/g')"
}

# ── Option parsing ────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --key-file) KEY_FILE="${2:?--key-file needs a value}"; shift 2 ;;
    --key-id) KEY_ID="${2:?--key-id needs a value}"; shift 2 ;;
    --issuer-id) ISSUER_ID="${2:?--issuer-id needs a value}"; shift 2 ;;
    --out-dir) OUT_DIR="${2:?--out-dir needs a value}"; shift 2 ;;
    --p12-password) P12_PASSWORD="${2:?--p12-password needs a value}"; shift 2 ;;
    --upload-secrets) UPLOAD_SECRETS=1; shift ;;
    --repo) GH_REPO="${2:?--repo needs a value}"; shift 2 ;;
    --check) CHECK_ONLY=1; shift ;;
    --force) FORCE=1; shift ;;
    -h | --help) usage 0 ;;
    *) echo "Unknown option: $1" >&2; usage 1 ;;
  esac
done

# ── Validation ────────────────────────────────────────────────────────────
need openssl ""
need curl ""
need jq " (on macOS: brew install jq)"

[ -n "$KEY_FILE" ] || { echo "Missing --key-file" >&2; usage 1; }
[ -f "$KEY_FILE" ] || die "API key file not found: $KEY_FILE"
[ -n "$ISSUER_ID" ] || { echo "Missing --issuer-id" >&2; usage 1; }
printf '%s' "$ISSUER_ID" | grep -Eq \
  '^[0-9a-fA-F-]{36}$' || die "--issuer-id does not look like a UUID: $ISSUER_ID"

if [ -z "$KEY_ID" ]; then
  # key IDs are 10 alphanumeric characters, tolerate renamed files like
  # AuthKey_XXXXXXXXXX_admin.p8
  if [[ "$(basename "$KEY_FILE")" =~ AuthKey_([A-Z0-9]{10}) ]]; then
    KEY_ID="${BASH_REMATCH[1]}"
  else
    die "cannot derive the key ID from '$KEY_FILE', pass it with --key-id"
  fi
fi

openssl pkey -in "$KEY_FILE" -noout 2> /dev/null \
  || die "$KEY_FILE is not a readable private key (.p8)"

if [ "$UPLOAD_SECRETS" = 1 ]; then
  need gh " (see https://cli.github.com)"
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# ── App Store Connect API ─────────────────────────────────────────────────
make_jwt() {
  local header payload signing_input now exp der r s
  now="$(date +%s)"
  exp="$((now + TOKEN_LIFETIME_SECONDS))"
  header="$(printf '{"alg":"ES256","kid":"%s","typ":"JWT"}' "$KEY_ID" | b64url)"
  payload="$(printf '{"iss":"%s","iat":%d,"exp":%d,"aud":"appstoreconnect-v1"}' \
    "$ISSUER_ID" "$now" "$exp" | b64url)"
  signing_input="${header}.${payload}"

  printf '%s' "$signing_input" \
    | openssl dgst -sha256 -sign "$KEY_FILE" -out "$TMP_DIR/sig.der" \
    || die "signing the API token with $KEY_FILE failed"

  # JWT wants the raw 64 byte R||S signature, openssl emits ASN.1 DER
  der="$(openssl asn1parse -inform DER -in "$TMP_DIR/sig.der" \
    | grep 'prim: INTEGER' | sed 's/.*://')"
  r="$(fixed32 "$(printf '%s\n' "$der" | sed -n 1p)")"
  s="$(fixed32 "$(printf '%s\n' "$der" | sed -n 2p)")"
  printf '%s.%s' "$signing_input" "$(hex2bin "${r}${s}" | b64url)"
}

# asc_api <method> <path> [json-body-file] -> HTTP status, body in $TMP_DIR/response.json
asc_api() {
  local method="$1" path="$2" body="${3:-}" jwt
  jwt="$(make_jwt)"
  curl -sS -o "$TMP_DIR/response.json" -w '%{http_code}' \
    -X "$method" \
    -H "Authorization: Bearer $jwt" \
    -H "Content-Type: application/json" \
    ${body:+--data-binary @"$body"} \
    "${API_BASE}${path}" \
    || die "network error calling ${API_BASE}${path}"
}

print_api_errors() {
  jq -r '.errors[]? | "  \(.status) \(.code): \(.title)\n    \(.detail // "")"' \
    "$TMP_DIR/response.json" 2> /dev/null || cat "$TMP_DIR/response.json"
}

# ── 1. credentials preflight ──────────────────────────────────────────────
echo "Checking API credentials (key ${KEY_ID}) ..."
status="$(asc_api GET '/certificates?limit=1')"
case "$status" in
  200)
    echo "  OK, the key can talk to the certificates API"
    ;;
  401)
    print_api_errors >&2
    die "authentication failed (401): key ID, issuer ID and .p8 file do not match, or the clock is off"
    ;;
  403)
    print_api_errors >&2
    die "the key is not allowed to read certificates (403). An 'App Manager' key cannot manage certificates, use a key with Admin access created by the Account Holder"
    ;;
  *)
    print_api_errors >&2
    die "unexpected HTTP $status from the certificates API"
    ;;
esac

if [ "$CHECK_ONLY" = 1 ]; then
  echo "Credentials check finished. Note: only creating a certificate proves"
  echo "that the key was generated by the Account Holder."
  exit 0
fi

# ── 2. private key + CSR ──────────────────────────────────────────────────
mkdir -p "$OUT_DIR"
PRIVATE_KEY="$OUT_DIR/developer-id.key"
CSR_FILE="$TMP_DIR/developer-id.csr"
CER_FILE="$OUT_DIR/developer-id.cer"
PEM_FILE="$OUT_DIR/developer-id.pem"
P12_FILE="$OUT_DIR/DeveloperIdApplication.p12"

if [ -f "$P12_FILE" ] && [ "$FORCE" != 1 ]; then
  die "$P12_FILE already exists, re-run with --force to replace it"
fi

if [ -f "$PRIVATE_KEY" ] && [ "$FORCE" != 1 ]; then
  echo "Reusing existing private key $PRIVATE_KEY"
else
  echo "Generating private key $PRIVATE_KEY ..."
  (umask 077 && openssl genrsa -out "$PRIVATE_KEY" 2048 2> /dev/null)
fi
openssl req -new -key "$PRIVATE_KEY" -out "$CSR_FILE" -subj "$CSR_SUBJECT" \
  || die "creating the certificate signing request failed"

# ── 3. certificate creation ───────────────────────────────────────────────
echo "Requesting the Developer ID Application certificate ..."
jq -n --rawfile csr "$CSR_FILE" \
  '{data: {type: "certificates", attributes: {
     certificateType: "DEVELOPER_ID_APPLICATION", csrContent: $csr}}}' \
  > "$TMP_DIR/request.json"

status="$(asc_api POST '/certificates' "$TMP_DIR/request.json")"
case "$status" in
  201)
    echo "  certificate created"
    ;;
  403)
    print_api_errors >&2
    die "Apple refused to create the certificate (403). Only the ACCOUNT HOLDER of the Apple Developer team can create Developer ID certificates: the API key must be a TEAM key generated by the Account Holder (Users and Access → Integrations → Team Keys). Being an Admin is not enough and individual keys cannot use the certificate endpoints. If the Account Holder is someone else, ask them to create such a key (or the certificate itself from the developer portal)"
    ;;
  *)
    print_api_errors >&2
    die "certificate creation failed with HTTP $status"
    ;;
esac

CERTIFICATE_ID="$(jq -r '.data.id // empty' "$TMP_DIR/response.json")"
jq -r '.data.attributes.certificateContent // empty' "$TMP_DIR/response.json" \
  > "$TMP_DIR/certificate.b64"
[ -s "$TMP_DIR/certificate.b64" ] || die "the API response contains no certificate"

openssl base64 -d -A < "$TMP_DIR/certificate.b64" > "$TMP_DIR/certificate.cer"
openssl x509 -inform DER -in "$TMP_DIR/certificate.cer" -out "$TMP_DIR/certificate.pem" \
  || die "the returned certificate is not valid DER"

# the certificate must embed the public half of our private key
if ! cmp -s \
  <(openssl x509 -in "$TMP_DIR/certificate.pem" -noout -pubkey) \
  <(openssl pkey -in "$PRIVATE_KEY" -pubout 2> /dev/null); then
  die "the returned certificate does not match $PRIVATE_KEY"
fi
mv "$TMP_DIR/certificate.cer" "$CER_FILE"
mv "$TMP_DIR/certificate.pem" "$PEM_FILE"
echo "  subject: $(openssl x509 -in "$PEM_FILE" -noout -subject | sed 's/^subject=//')"
echo "  expires: $(openssl x509 -in "$PEM_FILE" -noout -enddate | sed 's/^notAfter=//')"

# ── 4. .p12 export ────────────────────────────────────────────────────────
if [ -z "$P12_PASSWORD" ]; then
  [ -t 0 ] || die "no terminal to prompt for the .p12 password, pass --p12-password"
  read -rs -p "Password for the .p12 export: " P12_PASSWORD
  echo
  [ -n "$P12_PASSWORD" ] || die "the .p12 password must not be empty"
fi

(umask 077 && P12_PASSWORD="$P12_PASSWORD" openssl pkcs12 -export \
  -inkey "$PRIVATE_KEY" -in "$PEM_FILE" -out "$P12_FILE" \
  -passout env:P12_PASSWORD) \
  || die "exporting $P12_FILE failed"
echo "Wrote $P12_FILE"

# ── 5. optional secrets upload ────────────────────────────────────────────
if [ "$UPLOAD_SECRETS" = 1 ]; then
  gh_args=()
  [ -n "$GH_REPO" ] && gh_args+=(--repo "$GH_REPO")
  echo "Uploading CSC_LINK and CSC_KEY_PASSWORD ..."
  openssl base64 -A < "$P12_FILE" \
    | gh secret set CSC_LINK "${gh_args[@]}" --body - \
    || die "uploading CSC_LINK failed"
  gh secret set CSC_KEY_PASSWORD "${gh_args[@]}" --body "$P12_PASSWORD" \
    || die "uploading CSC_KEY_PASSWORD failed"
  echo "  done"
fi

# ── Summary ───────────────────────────────────────────────────────────────
echo
echo "Certificate ${CERTIFICATE_ID:-?} is ready."
if [ "$UPLOAD_SECRETS" != 1 ]; then
  echo "Upload the signing secrets with:"
  echo "  openssl base64 -A < '$P12_FILE' | gh secret set CSC_LINK --body -"
  echo "  gh secret set CSC_KEY_PASSWORD --body '<the .p12 password>'"
fi
echo "Remember the notarization secrets (see docs/macos-code-signing.md):"
echo "  gh secret set APPLE_ID / APPLE_APP_SPECIFIC_PASSWORD / APPLE_TEAM_ID"
echo
echo "Keep $PRIVATE_KEY and $P12_FILE safe, they are not recoverable from Apple."
